apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: demo
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      # memory_limiter:
      #   check_interval: 1s
      #   limit_percentage: 75
      #   spike_limit_percentage: 15
      # batch:
      #   send_batch_size: 10000
      #   timeout: 10s

    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: jaeger:4317
        tls:
          insecure: true
      otlp/tempo:
        endpoint: tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: true
      otlphttp:
        endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp
      otlphttp/mimir:
        endpoint: http://mimir.monitoring.svc.cluster.local:9009/otlp
      # prometheusremotewrite:
      #   endpoint: http://mimir.monitoring.svc.cluster.local/api/v1/push
      # prometheus:
      #   endpoint: "0.0.0.0:8889"
      #   send_timestamps: true
      #   namespace: otel-test
      #   const_labels:
      #     via: collector
      #   enable_open_metrics: true
      #   # resource_to_telemetry_conversion:
      #   #   enabled: true

    service:
      # telemetry:
        # traces:
        #   level: "debug"
        # logs:
        #   level: "debug"
      pipelines:
        traces:
          receivers: [otlp]
          # processors: []
          exporters: [otlp, otlp/tempo]
        # metrics:
        #   receivers: [otlp]
        #   processors: [memory_limiter, batch]
        #   exporters: [otlphttp/mimir, prometheus, debug]
        logs:
          receivers: [otlp]
          # processors: []
          exporters: [otlphttp]